### ISSUE TITLE
Make embeds customizable

### ISSUE THREAD

**Issue by nachoiacovino** [nftlabs/widgets#8]
We could add darkmode, change bg color, accent color, etc.

Some people have asked about this already.

**Comment by pingrishabh** [comment]
#33 Added a few to start with. Have a look!

**Comment by warengonzaga** [comment]
I believe customization is already in the build. Can we close this @nachoiacovino ?

**Comment by warengonzaga** [comment]
Closing this now as we have a different embed now.
